version: "1"
services:
  - type: web
    name: ai-email-organizer-frontend
    env: node
    region: oregon
    plan: starter
    buildCommand: npm run build:frontend
    startCommand: npm run start:frontend
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXTAUTH_URL
        fromService:
          type: web
          name: ai-email-organizer-frontend
          property: url
      - key: NEXTAUTH_SECRET
        sync: false
      - key: NEXT_PUBLIC_API_URL
        value: https://ai-email-organizer.fly.dev/api/v1
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
    autoDeploy: true
    branch: main
    rootDir: .
    buildFilter:
      paths:
        - app/**
        - components/**
        - lib/**
        - context/**
        - public/**
        - package.json
        - package-lock.json
        - next.config.ts
        - tailwind.config.ts
        - tsconfig.json
        - .env.example
      ignoredPaths:
        - server/**
        - prisma/**
        - tests/**
        - scripts/**
