name: ai-email-organizer
services:
- name: frontend
  source_dir: /
  github:
    repo: your-username/ai-email-organizer
    branch: main
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  build_command: npm install --legacy-peer-deps && npm run build:frontend
  envs:
  - key: NODE_ENV
    value: production
  - key: NEXTAUTH_URL
    value: ${APP_URL}
  - key: NEXTAUTH_SECRET
    value: ${NEXTAUTH_SECRET}
  - key: GOOGLE_CLIENT_ID
    value: ${GOOGLE_CLIENT_ID}
  - key: GOOGLE_CLIENT_SECRET
    value: ${GOOGLE_CLIENT_SECRET}
  - key: OPENAI_API_KEY
    value: ${OPENAI_API_KEY}