name: ai-email-organizer-frontend
services:
- name: frontend
  source_dir: /
  github:
    repo: ifeora-emeka/ai-email-organizer
    branch: main
  build_command: npm install -f && npm run db:generate && npm run build:frontend
  run_command: npm run start:frontend
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 3000
  envs:
  - key: NODE_ENV
    value: production
  - key: NEXTAUTH_URL
    value: ${APP_URL}
  - key: NEXTAUTH_SECRET
    value: ${NEXTAUTH_SECRET}
    type: SECRET
  - key: GOOGLE_CLIENT_ID
    value: ${GOOGLE_CLIENT_ID}
    type: SECRET
  - key: GOOGLE_CLIENT_SECRET
    value: ${GOOGLE_CLIENT_SECRET}
    type: SECRET
  - key: NEXT_PUBLIC_API_URL
    value: ${NEXT_PUBLIC_API_URL}
  - key: DATABASE_URL
    value: ${DATABASE_URL}
    type: SECRET
  - key: OPENAI_API_KEY
    value: ${OPENAI_API_KEY}
    type: SECRET
